include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Custom rules
    prefer_single_quotes: true
    prefer_relative_imports: true
    always_use_package_imports: false

    # Relaxed rules for development
    public_member_api_docs: false
    lines_longer_than_80_chars: false
