// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4lDKJFk7w3myhcSHiPIke224zBY5tjRw',
    appId: '1:80422483124:web:896761028906df5ba6d3e1',
    messagingSenderId: '80422483124',
    projectId: 'skilllist-app',
    authDomain: 'skilllist-app.firebaseapp.com',
    storageBucket: 'skilllist-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrkLNPeY7EIGvBj9G3Xfc_hb-nlZ_khTk',
    appId: '1:80422483124:android:bc662fe5ee86c738a6d3e1',
    messagingSenderId: '80422483124',
    projectId: 'skilllist-app',
    storageBucket: 'skilllist-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKEVmRQR-T3X_oaYbDfUxhonE0-JmTXWc',
    appId: '1:80422483124:ios:bd7893dcdb535d1ca6d3e1',
    messagingSenderId: '80422483124',
    projectId: 'skilllist-app',
    storageBucket: 'skilllist-app.firebasestorage.app',
    iosBundleId: 'com.kamurandev.skilllist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKEVmRQR-T3X_oaYbDfUxhonE0-JmTXWc',
    appId: '1:80422483124:ios:bd7893dcdb535d1ca6d3e1',
    messagingSenderId: '80422483124',
    projectId: 'skilllist-app',
    storageBucket: 'skilllist-app.firebasestorage.app',
    iosBundleId: 'com.kamurandev.skilllist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4lDKJFk7w3myhcSHiPIke224zBY5tjRw',
    appId: '1:80422483124:web:ff6e7c53731a560aa6d3e1',
    messagingSenderId: '80422483124',
    projectId: 'skilllist-app',
    authDomain: 'skilllist-app.firebaseapp.com',
    storageBucket: 'skilllist-app.firebasestorage.app',
  );
}
